language = "C"

[export]
exclude = ["DepKind", "VersionRange", "DepEntry", "JarInJar", "DepReport",
           "ForgeModFormat", "PluginType", "ModType", "ModMetadata",
           "Registry", "ModHandler",
           "FabricModMetadata", "ModsTomlMetadata", "BukkitPluginMetadata",
           "PaperPluginMetadata", "ForgeLegacyModEntry", "ForgeLegacyDisplay",
           "FabricContact", "FabricJarEntry", "ModsTomlMod", "ModsTomlDependency",
           "ModsTomlMixin"]

[parse]
parse_deps = false
clean = false
