version = 1
platform = "github"
lang = "rust"

[[artifacts]]
type = "bin"
name = "modcrawl"
outputName = "{name}-{os}-{arch}-{abi}"

[[artifacts]]
type = "lib"
name = "modcrawl"
outputName = "lib{name}-{os}-{arch}-{abi}"
headers = true

# --- LINUX BIN ---
[[targets]]
id = "linux-gnu-bin"
for = "modcrawl"
type = "bin"
os = "linux"
arch = ["x86_64", "arm64"]
abi = "gnu"
features = ["cli"]
packages = ["bin"]

[[targets]]
id = "linux-musl-bin"
for = "modcrawl"
type = "bin"
os = "linux"
arch = ["x86_64", "arm64"]
abi = "musl"
defaultFeatures = false
features = ["cli"]
packages = ["bin"]

# --- LINUX LIB ---
[[targets]]
id = "linux-gnu-lib"
for = "modcrawl"
type = "lib"
os = "linux"
arch = ["x86_64", "arm64"]
abi = "gnu"
packages = ["tar.gz"]

[[targets]]
id = "linux-musl-lib"
for = "modcrawl"
type = "lib"
os = "linux"
arch = ["x86_64", "arm64"]
abi = "musl"
defaultFeatures = false
packages = ["tar.gz"]

# --- WINDOWS BIN ---
[[targets]]
id = "windows-msvc-bin"
for = "modcrawl"
type = "bin"
os = "windows"
arch = ["x86_64", "arm64"]
abi = "msvc"
features = ["cli"]
packages = ["bin"]

# --- WINDOWS LIB ---
[[targets]]
id = "windows-msvc-lib"
for = "modcrawl"
type = "lib"
os = "windows"
arch = ["x86_64", "arm64"]
abi = "msvc"
packages = ["zip"]

# --- MACOS BIN ---
[[targets]]
id = "macos-bin"
for = "modcrawl"
type = "bin"
os = "macos"
arch = ["x86_64", "arm64"]
features = ["cli"]
packages = ["bin"]

# --- MACOS LIB ---
[[targets]]
id = "macos-lib"
for = "modcrawl"
type = "lib"
os = "macos"
arch = ["x86_64", "arm64"]
packages = ["tar.gz"]

# --- PUBLISH ---
[[publish]]
type = "builtin"
builtin = "download_artifact"
targets = "all"

[[publish]]
type = "builtin"
builtin = "github_release"
targets = "all"

[[publish]]
type = "composite"
name = "Publish to crates.io"
action = "cargo-publish"
secrets = ["CRATES_TOKEN"]
targets = "once"
